security:
  user:
    shortName: user
    password: Passw0rd

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    username: sa
    password:
    url: jdbc:h2:~/test
    driver-class-shortName: org.h2.Driver

