security:
  user:
    shortName: user
    password: Passw0rd
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    username: root
    password: mypass
    url: jdbc:mariadb://localhost:3306/DB
    driver-class-shortName: org.mariadb.jdbc.Driver

